[package]
name = "ferriskv-auth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ferriskv-core = { workspace = true }
jsonwebtoken = { workspace = true }
argon2 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
blake3 = { workspace = true }

[dev-dependencies]
divan = { workspace = true }

[[bench]]
name = "auth"
harness = false
