[package]
name = "ferriskv-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "ferriskv-node"
path = "src/main.rs"

[dependencies]
ferriskv-core = { workspace = true }
ferriskv-proto = { workspace = true }
ferriskv-auth = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
axum = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
config = { workspace = true }
reqwest = { workspace = true }
governor = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
parking_lot = { workspace = true }
blake3 = { workspace = true }
crc32fast = { workspace = true }
lz4_flex = { workspace = true }
bloomfilter = { workspace = true }
futures = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }

[dev-dependencies]
jsonwebtoken = { workspace = true }
tempfile = { workspace = true }
proptest = { workspace = true }
